# Generated by Django 5.2.7 on 2025-10-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='nome')),
                ('lastname', models.CharField(max_length=20, verbose_name='sobrenome')),
                ('user', models.CharField(max_length=20, verbose_name='usuario')),
                ('password', models.CharField(max_length=255, verbose_name='senha')),
            ],
        ),
    ]
