# Generated by Django 5.2.7 on 2025-10-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='valor')),
                ('parcel', models.IntegerField(verbose_name='parcela')),
                ('firstParcelDate', models.DateField(verbose_name='data da primeira parcela')),
            ],
        ),
        migrations.DeleteModel(
            name='purchase',
        ),
    ]
